# Generated by Django 5.2 on 2025-04-06 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('titel', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('verlag', models.CharField(max_length=200)),
                ('verlagungsdatum', models.DateField()),
                ('wiederbeschaffungswert', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Schüler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schueler_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('vorname', models.CharField(max_length=200)),
                ('klasse', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('gesperrtBis', models.DateField()),
                ('anzahlVerspätungen', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BuchExemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventarnummer', models.CharField(max_length=200)),
                ('anschaffungsdatum', models.DateField()),
                ('zustand', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('buch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buchexemplare', to='myapp.buch')),
            ],
        ),
        migrations.CreateModel(
            name='Ausleihe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausleihdatum', models.DateField()),
                ('rueckgabedatum', models.DateField(blank=True, null=True)),
                ('fälligkeitsdatum', models.DateField()),
                ('istZurückgegeben', models.BooleanField(default=False)),
                ('erinnerungGesendet', models.BooleanField(default=False)),
                ('mahnungGesendet', models.BooleanField(default=False)),
                ('exemplar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aktuelle_ausleihe', to='myapp.buchexemplar')),
                ('schüler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausleihen', to='myapp.schüler')),
            ],
        ),
        migrations.CreateModel(
            name='Mahnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellungsdatum', models.DateField()),
                ('mahnungsTyp', models.CharField(max_length=200)),
                ('istBearbeitet', models.BooleanField(default=False)),
                ('ausleihe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahnungen', to='myapp.ausleihe')),
            ],
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechnungsNummer', models.CharField(max_length=200)),
                ('datum', models.DateField()),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('istBezahlt', models.BooleanField(default=False)),
                ('ausleihe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechnungen', to='myapp.ausleihe')),
            ],
        ),
    ]
