# Generated by Django 5.2 on 2025-04-06 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schüler',
            name='anzahlVerspätungen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schüler',
            name='gesperrtBis',
            field=models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
