# Generated by Django 5.2 on 2025-04-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_schüler_anzahlverspätungen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchexemplar',
            name='status',
            field=models.CharField(choices=[('verfügbar', 'Verfügbar'), ('ausgeliehen', 'Ausgeliehen'), ('reserviert', 'Reserviert'), ('reparatur', 'In Reparatur'), ('verloren', 'Verloren')], default='verfügbar', max_length=200),
        ),
    ]
