# Generated by Django 5.2 on 2025-04-06 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_buchexemplar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausleihe',
            name='exemplar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausleihen', to='myapp.buchexemplar'),
        ),
    ]
