# Generated by Django 5.2 on 2025-04-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_schüler_schueler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchexemplar',
            name='status',
            field=models.CharField(choices=[('verfügbar', 'Verfügbar'), ('ausgeliehen', 'Ausgeliehen'), ('verloren', 'Verloren'), ('beschädigt', 'Beschädigt')], default='verfügbar', max_length=20),
        ),
    ]
